sudo: required
services:
  - docker

before_install:
  - docker build -t rickhui/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rickhui/react-test npm run test

after_success:
  - docker build -t rickhui/multi-client ./client
  - docker build -t rickhui/multi-nginx ./nginx
  - docker build -t rickhui/multi-server ./server
  - docker build -t rickhui/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rickhui/multi-client
  - docker push rickhui/multi-nginx
  - docker push rickhui/multi-server
  - docker push rickhui/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react-demo"
#   env: "DockerReactDemo-env"
#   bucket_name: "elasticbeanstalk-us-west-2-081763001095"
#   bucket_path: "docker-react-demo"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
